#!/usr/bin/env python3

import sys, logging, argparse

logging.basicConfig(level=logging.INFO, format="%(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

parser = argparse.ArgumentParser(prog="Universal Home Builder")
parser.add_argument("config", type=str, help="Path to the entry config file")
parser.add_argument(
    "--show-exceptions",
    action="store_true",
    help="Show exceptions in the output for debugging purposes",
)
parser.set_defaults(show_exceptions=False)
args = parser.parse_args()

from src.ConfigFile import ConfigFile
from src.ConfigEntity import ConfigEntity

try:
    entry_config = ConfigEntity(ConfigFile(args.config))
except Exception as e:
    logger.error(f"Build failed: {e}")
    if args.show_exceptions:
        raise e
    sys.exit(1)

# from src.ConfigBuilder import ConfigBuilder
# from src.HomeBuilder import HomeBuilder

# try:
#     conf_builder = ConfigBuilder(args.config)
#     home_builder = HomeBuilder(conf_builder.build())
#     home_builder.build()
#     logger.info("Build successful!")
# except Exception as e:
#     logger.error(f"Build failed: {e}")
#     if args.show_exceptions:
#         raise e
#     sys.exit(1)
