#!/usr/bin/env python3

import sys, logging

from src.ConfigBuilder import ConfigBuilder
from src.HomeBuilder import HomeBuilder

logging.basicConfig(level=logging.INFO, format="%(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

if len(sys.argv) < 2:
    logger.error(
        f"""
        You must specify entry config file.
        Usage: {sys.argv[0]} <path/to/host.toml>
        """
    )
    sys.exit(1)

try:
    conf_builder = ConfigBuilder(sys.argv[1])
    home_builder = HomeBuilder(conf_builder.build())
    home_builder.build()
    logger.info("Build successful!")
except Exception as e:
    logger.error(f"Build failed: {e}")
    sys.exit(1)
