#!/usr/bin/env python3


import sys, argparse

parser = argparse.ArgumentParser(prog="Universal Home Builder")
parser.add_argument("config", type=str, help="Path to the entry config file")
parser.add_argument(
    "--show-exceptions",
    action="store_true",
    help="Show exceptions in the output for debugging purposes",
)
parser.set_defaults(show_exceptions=False)
args = parser.parse_args()


import logging
from src.LoggingFormatter import Formatter

logger = logging.getLogger("Universal Home Builder")
logger.setLevel(logging.INFO)
handler = logging.StreamHandler()
handler.setLevel(logging.INFO)
handler.setFormatter(Formatter())
logger.addHandler(handler)


from src.ConfigFile import ConfigFile
from src.ConfigEntity import ConfigEntity
from src.HomeBuilder import HomeBuilder

try:
    home_builder = HomeBuilder(ConfigEntity(ConfigFile(args.config)))
    home_builder.build()
except Exception as e:
    logger.error(f"Build failed: {e}")
    if args.show_exceptions:
        raise e
    sys.exit(1)
